dist: trusty
sudo: required
language: node_js
node_js:
  - "7.6"

matrix:
  include:
    - os: linux
      dist: trusty
      before_install: 
      - sudo add-apt-repository ppa:ethereum/ethereum -y
      - sudo apt-get update
      - sudo apt-get install build-essential -y

install: 
  - sh ./install.sh

script: 
  - sh ./run.sh
