[parity]
chain ="dev"

[account]
unlock=["0x00a329c0648769a73afac7f9381e08fb43dbea72"]
password=["password"]

[rpc]
port=4242
apis=["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]